### ISSUE TITLE
Broken after update

### ISSUE THREAD

**Issue by gprime31** [daxAKAhackerman/XSS-Catcher#30]
![2022-01-06_08-57](https://user-images.githubusercontent.com/44535257/148394022-7b77bf29-e426-4a34-9db2-dd68cd6f691f.png)

**Comment by gprime31** [comment]
it auto logs in
can't make a user
can't do anything  really
tried deleting the docker images and git clone from scratch 
this is the result.
any ideas on how to fix?

**Comment by daxAKAhackerman** [comment]
Hey 👋 From what version did you update? I've testing updating from the previous version (v1.7.0) and deploying from scratch (after deleting all docker images, volumes and cloning the repo from scratch) and it's working for me. 

Could you show me logs generated by the backend container (which seems to be at fault here). You can do so by running `docker logs xss-catcher_backend_1`.

**Comment by gprime31** [comment]
![2022-01-06_20-38](https://user-images.githubusercontent.com/44535257/148477287-133e8f28-839d-4cb4-b9ba-e2a7d526c0fa.png)
![2022-01-06_20-38_1](https://user-images.githubusercontent.com/44535257/148477317-759bb716-3e2c-4aa3-aaec-e416305add61.png)
![2022-01-06_20-39](https://user-images.githubusercontent.com/44535257/148477318-95f6d75a-f7ce-4d7a-871f-9641dc506cd6.png)

**Comment by gprime31** [comment]
not sure what version i updated from... it's been awhile. 
But i removed all docker containers and images and re git cloned and same result.
so no idea what is going on.

**Comment by daxAKAhackerman** [comment]
Hmm seems like it's the database container which is having trouble starting 🤔 I believe running `docker logs xss-catcher_db_1` will give us the reason why it is not working!

**Comment by gprime31** [comment]
![2022-01-06_21-03](https://user-images.githubusercontent.com/44535257/148479527-97061d8b-b314-4bd7-942a-0a0672b22707.png)

**Comment by gprime31** [comment]
Thanks for all the help btw. :)

**Comment by gprime31** [comment]
shoulden't this update when I deleted everything and installed fresh?

**Comment by gprime31** [comment]
> shoulden't this update when I deleted everything and installed fresh?
Postgreg is part of the docker pull right?

**Comment by daxAKAhackerman** [comment]
Yes, actually the problem comes from the fact that the postgres version in the db container was updated, but the data was created using postgres13, and this is still persisted in `/var/lib/docker/volumes`. That's why I hardcoded the postgres version to 14 in the latest update (I didn't know better before 😅). 

You have two ways to fix this: 
A) First stop XSS-Catcher using `make stop`, then run `docker volume rm xss-catcher_xss-db`. This will effectively delete the XSS-Catcher data and allow you to start from a clean postgres14 database using `make start` 🙂 However, this will delete your data.
B) If your data is important and you cannot just delete the database, you can go into `docker-compose.yml` and change line 9 to `postgres:13.5-alpine3.15`. Then, run `make update`. This will allow you to run on postgres13 instead of 14. 

If the data is not important, I would personally go for option A. 

Let me know if it works!

**Comment by gprime31** [comment]
Option A worked perfectly.
Thanks very much!!!!

**Comment by daxAKAhackerman** [comment]
Glad to hear that! My pleasure! 🎉 🥳
